bjjmap:
  build: .
  ports:
    - 3000:3000
  volumes:
    - /Users/jj010933/personal/BJJMap/public:/go/src/app/public
    - go-modules:/go/pkg/mod
  links:
    - database
  environment:
    - MAIN_DB_NAME=bjjmap_database_1
    - GOOGLE_APPLICATION_CREDENTIALS=/go/src/app/bjjmap-e68a1-firebase-adminsdk-hi0bs-61779b1497.json

database:
  image: mongo:latest
