bjjmap:
  build: .
  ports:
    - 3000:3000
  volumes:
    - ~/BJJMap:/user/home/jerehmiah/volumes/bjjmap
  links:
    - database
  environment:
    - MAIN_DB_NAME=bjjmap_database_1

database:
  image: mongo:latest
