bjjmap:
  build: .
  ports:
    - 3000:3000
  volumes:
    - /home/jerehmiah/BJJMap/public:/go/src/app/public
  links:
    - database
  environment:
    - MAIN_DB_NAME=bjjmap_database_1

database:
  image: mongo:latest
